### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lgraziani2712** [atlassian-labs/storybook-addon-performance#50]
When I'm trying to meassure the performance of a story with decorators with preview hooks, the renders throws an error:

> Storybook preview hooks can only be called inside decorators and story functions

![image](https://user-images.githubusercontent.com/15050200/91604718-8e70e500-e945-11ea-9056-736a3be11e4e.png)

If I remove the decorator's preview hooks, everything works correctly.

- Repro: https://github.com/lgraziani2712/sb-perf-preview-decorators-bug

Than you for your work!

**Comment by markelarizaga** [comment]
I'm experiencing the same.
@lgraziani2712 maybe you want to update the title of this issue to make it more descriptive, I clicked on it to check if by any chance was the same thing I'm reproducing, and it was!
However maybe other people just ignore the issue if it just says "Bug".

**Comment by lgraziani2712** [comment]
Thank you for noticing this, @markelarizaga! I was pretty sure I did write a descriptive title, but wasn't the case!

It is now fixed :)

**Comment by SatorCube** [comment]
Can confirm the same issue. It also happens when you the performance addon in conjunction with the popular [pseudo-states](https://storybook.js.org/addons/storybook-addon-pseudo-states/) addon. As of right now, they are incompatible because of this bug. :"(

**Comment by iyobo** [comment]
Same issue when used i conjunction with storybook-miragejs.

Sadly, the only way to use this addon is to make sure other decorators that come before it in the chain do not use storybook hooks e.g useChannel, useParams, etc. Using React hooks are fine.

Was able to work-around by recreating the storybook-miragejs addon functionality I needed from scratch using purely react hooks. Nonetheless, this issue is very limiting for most realistic storybook implementations.

**Comment by viktor-panasiuk-97** [comment]
The issue is still relevant. In case you use preview hooks, the package does not work - 
![image](https://github.com/atlassian-labs/storybook-addon-performance/assets/81861520/25e579be-e6c7-4067-b14c-8257252b0e7a)

**Comment by trouba** [comment]
This issue is still relevant, I've got the same error when using `useArgs` in a story
